---
- name: Setup docker-compose.
  hosts: all
  become: true

  vars:
  tasks:
    - name: Get primary network interface address.
      ansible.builtin.set_fact:
        server_ip: "{{ vars['ansible_eno1']['ipv4']['address'] }}"

    - name: Ensure that /opt/docker/main is exist.
      ansible.builtin.file:
        path: /opt/docker/main
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy template docker-compose.yaml.
      ansible.builtin.template:
        src: docker-compose.yaml.j2
        dest: /opt/docker/main/docker-compose.yaml
        owner: root
        group: root
        mode: '0644'
      
    - name: Start docker compose.
      ansible.builtin.command:
        cmd: "docker compose up -d"
        chdir: /opt/docker/main
      register: _rc
      failed_when: 
        - _rc.rc != 0
